### ISSUE TITLE
Make all examples compile

### ISSUE THREAD

**Issue by jchavarri** [glennsl/bucklescript-ffi-cheatsheet#3]
I generally copy these recipes and paste them on the online repl to figure out what I need. Some of them currently don't compile like:

```ocaml
external f : 'self -> 'ret = "" [@@bs.get]
let ret = f self
```

would you be open to a PR that replaces `'self` with `string` or `int` and make each recipe self-contained so all the examples compile straight away? Ideally, with examples that are meaningful from the "real world" :) I'm not sure if that breaks the original purpose of this cheatsheet.

For example, for `bs.get`:
```ocaml
type textarea
external make_textarea : value:string -> textarea = ""[@@bs.obj ]
let greeting_textarea = make_textarea ~value:"hello"
external get_value : textarea -> string = "value"[@@bs.get ]
let text = get_value greeting_textarea
```

**Comment by glennsl** [comment]
What makes it invalid? Just that `self` is not defined? The type variables and values are named in a meaningful and mnemonic way, so you can easily connect them and the roles they have. Using types such as `int` and `string`, and presumably using literals for the application, would go against this purpose.

With "real world" examples you'll have to make an effort understand the problem before you can understand the code, which might work better as a tutorial, but less well as a cheatsheet. Unless you can do the former without compromising the latter, I think I'll go with a "no" on this.

Thanks for the suggestion though :)

**Comment by jchavarri** [comment]
I thought that could be the case :) The tutorial vs cheatsheet comparison you do makes total sense 👍
